### ISSUE TITLE
Everyone's circle images are different sizes

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/interactiveaudiolab.github.io#2]
Standardize image sizes on this page:  https://interactiveaudiolab.github.io/people/

**Comment by interactiveaudiolab** [comment]
Idea: make sure photos have fixed dimension (or fixed relative dimension in `em` units)

**Comment by maxrmorrison** [comment]
Should be fixed. The fix was to fix the width/height in `rem` units and specifying the `overflow` and `object-fit` css parameters
